Task 1 Array Creation and Properties

In [2]:
# Import necessary libraries
import numpy as np

# 1. 1D array of 100 random integers between 1 and 50
array_1d = np.random.randint(1, 51, size=100)

# 2. 2D array of shape (5, 6) filled with ones, then converted to integer
array_2d = np.ones((5, 6)).astype(int)

# 3. 1D array of 20 evenly spaced values between 0 and 100
array_linspace = np.linspace(0, 100, 20)

# 4. 3x3 identity matrix
array_identity = np.eye(3)

# Function to display array properties
def display_properties(arr, name):
    print(f"--- {name} ---")
    print("Array:\n", arr)
    print("Shape:", arr.shape)
    print("Number of dimensions:", arr.ndim)
    print("Total number of elements:", arr.size)
    print("Data type:", arr.dtype)
    print("Memory size per element (bytes):", arr.itemsize)
    print("\n")

# Display properties
display_properties(array_1d, "1D Random Integers Array")
display_properties(array_2d, "2D Ones Array")
display_properties(array_linspace, "1D Linspace Array")
display_properties(array_identity, "3x3 Identity Matrix")

--- 1D Random Integers Array ---
Array:
 [30  5 22 49  9 19 41 49 10 23 43 41  2 30 18 18 41 32  6 36 44  7 31 24
 48 29 13 26 43 11 45 46 19 44  4 44 15 12 38 14 41 48 21 17 49 14 17 29
  3 16 40  9 29 16 15 25 18 44 21 19  5 20  9 48 42 34 23  4 47 14 35 39
 26 16  9 23 36 40 39 13 24  4 45 27 45 22 19 44 45 15 49 26 37 34 18 17
  6 12 48 18]
Shape: (100,)
Number of dimensions: 1
Total number of elements: 100
Data type: int32
Memory size per element (bytes): 4


--- 2D Ones Array ---
Array:
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Shape: (5, 6)
Number of dimensions: 2
Total number of elements: 30
Data type: int64
Memory size per element (bytes): 8


--- 1D Linspace Array ---
Array:
 [  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
Shape

1) np.random.randint() generates random integers in a specified range.

2) np.ones() creates an array filled with 1s; .astype(int) converts float to integer.

3) np.linspace() generates evenly spaced values between start and end points.

4) np.eye() creates an identity matrix.

5) arr.shape, arr.ndim, arr.size, arr.dtype, and arr.itemsize provide array metadata.

Task 2 Memory and Speed Comparison

In [4]:
import sys
import time

# Create Python list and NumPy array with 10,000 integers
list_data = list(range(1, 10001))
numpy_data = np.array(list_data)

# Memory consumption
list_memory = sys.getsizeof(list_data)
numpy_memory = numpy_data.nbytes

print(f"Memory used by Python list: {list_memory} bytes")
print(f"Memory used by NumPy array: {numpy_memory} bytes")

# Speed comparison: element-wise addition
# Lists
list_data2 = list(range(1, 10001))
start = time.time()
list_sum = [a + b for a, b in zip(list_data, list_data2)]
end = time.time()
list_time = end - start

# NumPy
numpy_data2 = np.array(list_data2)
start = time.time()
numpy_sum = numpy_data + numpy_data2
end = time.time()
numpy_time = end - start

print(f"\nTime taken for Python list addition: {list_time:.6f} seconds")
print(f"Time taken for NumPy array addition: {numpy_time:.6f} seconds")
print(f"NumPy is {list_time / numpy_time:.2f} times faster than Python lists")

Memory used by Python list: 80056 bytes
Memory used by NumPy array: 80000 bytes

Time taken for Python list addition: 0.001925 seconds
Time taken for NumPy array addition: 0.000211 seconds
NumPy is 9.10 times faster than Python lists


NumPy arrays store homogeneous types in contiguous memory(less memory)

Task 3 Practical Application

In [5]:
# Generate sales data: 30 days x 4 products, random sales 100-1000
sales = np.random.randint(100, 1001, size=(30, 4))

# Total sales per product
total_sales_per_product = sales.sum(axis=0)

# Average daily sales
average_daily_sales = sales.mean(axis=1)

# Day with maximum total sales
day_max_sales = np.argmax(sales.sum(axis=1)) + 1

# Product with minimum average sales
product_min_avg = np.argmin(sales.mean(axis=0)) + 1

# Convert sales to float32 to save memory
sales_float32 = sales.astype(np.float32)
memory_saved_per_element = sales.itemsize - sales_float32.itemsize

# Display results
print("Sales Data (first 5 days):\n", sales[:5])
print("\nTotal sales per product:", total_sales_per_product)
print("Average daily sales:", average_daily_sales[:5])
print(f"Day with maximum total sales: Day {day_max_sales}")
print(f"Product with minimum average sales: Product {product_min_avg}")
print(f"Memory saved per element after converting to float32: {memory_saved_per_element} bytes")

Sales Data (first 5 days):
 [[414 299 958 418]
 [128 390 694 576]
 [196 322 950 326]
 [742 773 743 494]
 [222 303 153 578]]

Total sales per product: [13670 17320 15997 17812]
Average daily sales: [522.25 447.   448.5  688.   314.  ]
Day with maximum total sales: Day 11
Product with minimum average sales: Product 1
Memory saved per element after converting to float32: 0 bytes


1) np.random.randint() simulates sales data.

2) np.argmax() finds the index of maximum total sales and np.argmin() finds the index of minimum average sales.

3) Converting to float32 reduces memory usage