In [3]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

# Task 1 : Print shape and mean temperature per station :
print("Shape of the data array:", data.shape)
mean_per_station = np.mean(data, axis=1)
print("Mean temperature per station:",mean_per_station)

Shape of the data array: (4, 5)
Mean temperature per station: [25.3  23.78 26.58 25.26]


In [5]:
# Task 2: Extract all records above 28 using boolean masking
above_28 = data[data > 28]
print("Temperature records above 28°C:", above_28)

Temperature records above 28°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


In [7]:
# Task 3 : Normaize to range [0,1]
normalized = (data - data.min()) / (data.max() - data.min())
print("Normaize Data:\n",np.round(normalized,2))

Normaize Data:
 [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
